vrrp_instance VI_1 {
    state MASTER
    interface enp3s0
    virtual_router_id 51
    priority 150
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass HA123
    }

    unicast_src_ip 192.168.1.74
    unicast_peer {
        192.168.1.77
    }

    virtual_ipaddress {
        192.168.1.201/24
    }
}



vrrp_instance VI_1 {
    state BACKUP
    interface wlo1
    virtual_router_id 51
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass HA123
    }

    unicast_src_ip 192.168.1.77
    unicast_peer {
        192.168.1.74
    }

    virtual_ipaddress {
        192.168.1.201/24
    }
}




