{
 "title": "NATS Metrics",
 "tags": [ "NATS" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(gnatsd_varz_uptime, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status do NATS (Cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connections (Cluster Sum)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnatsd_connz_num_connections)"
    }
   ]
  },
  {
   "title": "Total Slow Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnatsd_varz_slow_consumers)"
    }
   ]
  },
  {
   "title": "Message Rate per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(gnatsd_varz_in_msgs[1m])", "legendFormat": "{{instance}} In" },
    { "expr": "rate(gnatsd_varz_out_msgs[1m])", "legendFormat": "{{instance}} Out" }
   ]
  },
  {
   "title": "Bandwidth Rate per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(gnatsd_varz_in_bytes[1m])", "legendFormat": "{{instance}} In" },
    {
     "expr": "rate(gnatsd_varz_out_bytes[1m])",
     "legendFormat": "{{instance}} Out"
    }
   ]
  }
 ]
}