global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'chaos_nodes'
    static_configs:
      # Nó Local
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'local-node'
          nodename: 'local-node'

      # Consul Nodes
      - targets: ['172.21.0.3:9100']
        labels:
          instance: 'server1'
          nodename: 'server1'

      - targets: ['172.21.0.4:9100']
        labels:
          instance: 'server2'
          nodename: 'server2'

      - targets: ['172.21.0.2:9100']
        labels:
          instance: 'server3'
          nodename: 'server3'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
