global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'chaos_nodes'
    static_configs:
      # Nó Local
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'local-node'
          nodename: 'local-node'

  # --- NOVO: Descoberta Automática de Serviços via Consul ---
  - job_name: 'consul_services'
    consul_sd_configs:
      - server: 'consul-server1:8500' # Prometheus conecta ao Consul Server 1
        services: [] # Descobre todos os serviços. Podes filtrar ex: ['api', 'web']
    relabel_configs:
      # Só faz scrape se o serviço tiver a tag "metrics" (Opcional, mas boa prática)
      # - source_labels: [__meta_consul_tags]
      #   regex: .*,metrics,.*
      #   action: keep
      
      # Usa o nome do serviço como label 'job'
      - source_labels: [__meta_consul_service]
        target_label: job

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
