apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: LOKI_CHAOS
    url: http://loki:3100
    access: proxy
    jsonData:
      maxLines: 1000

  - name: Jaeger
    type: jaeger
    uid: JAEGER_CHAOS
    url: http://jaeger:16686
    access: proxy
    jsonData:
      nodeGraph:
        enabled: true
